name: indihome
description: AR based Interior Designing Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_plus: ^5.0.0
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
